### ISSUE TITLE
Dune stanza `executables`

### ISSUE THREAD

**Issue by tek** [tweag/okapi#5]
Currently, each set of modules is associated with one `library` or `executable`.
When converting one of these components to Bazel rules, its modules get reified to rules as well.

The stanza `executables` produces multiple executables but is associated with a module set as well, which will then be reified for *each* of the executables, resulting in duplicates.

The solution might be to decouple the module sets from the component and reify modules separately.

**Comment by mobileink** [comment]
FWIW, the OBazl tools work bottom-up.  First we create a module database that maps qualified module names to module specs, that include sig and struct filenames and dependencies.  With this we can emit ocaml_module and ocaml_signature targets independent of dune.  Then converting dune library stanzas (=> ocaml_ns_archive) and executables is orthogonal to emitting module and sig targets.

**Comment by tek** [comment]
yeah, it's mostly handled similarly here, but at some point it is interwoven with dune, so this has to be removed
